# NUMPY

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5]) #ndarray creation
print(arr)

[1 2 3 4 5]


In [4]:
print(np.__version__) #to check the numpy version 

1.23.5


In [5]:
type(arr)

numpy.ndarray

In [6]:
arry= np.array((10,20,30,40,50))
print(arry)

[10 20 30 40 50]


# multidimenstional array

In [9]:
yash = np.array(61)
viraj = np.array((58,5))
ram = np.array(((1,2,3),(1,3,4)))
sita = np.array((((1,2,3,4,5),(5,6,7,8,9)),((9,8,7,6,4),(5,4,3,2,1))))
shiva = np.array(((((1,2,3,4,5),(5,6,7,8,9)),((9,8,7,6,4),(5,4,3,2,1))),(((1,2,3,4,5),(5,6,7,8,9)),((9,8,7,6,4),(5,4,3,2,1)))))

In [10]:
print(yash.ndim)
print(viraj.ndim)
print(ram.ndim)
print(sita.ndim)
print(shiva.ndim)

0
1
2
3
4


In [14]:
ram[1] #indexing the array

array([1, 3, 4])

In [15]:
ram[1,2] #double indexing 

4

In [16]:
#adding the index values directly 
viraj[0] + viraj[1]

63

In [21]:
x =  np.array(((1,2,3),(1,3,4)))
#negative indexing in numpy array nd array 
print(x[-1,-3])
print(x[0,-1])

1
3


In [28]:
y = np.array((1,2,3,4,5,6,7,8,9,10))
print(y[:5])
print(y[3:])
print(y[:])
print(y[::2])

[1 2 3 4 5]
[ 4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


# Data type in ndarray

## 
    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


In [32]:
fruits = np.array(("apple","pineapple","balda wala apple"))
print(fruits)
print(fruits.dtype)

['apple' 'pineapple' 'balda wala apple']
<U16


In [30]:
st_numbers = np.array((1,2,3,4,5),dtype='S')
print(st_numbers)
print(st_numbers.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [37]:
#float array to int array 
int_Float = np.array((1.2,2.2,3.4,0.1))
print(int_Float)

[1.2 2.2 3.4 0.1]


In [38]:
#use astype function
Float_int = int_Float.astype('i')
print(Float_int)
print(Float_int.dtype)

[1 2 3 0]
int32


In [39]:
F_i= int_Float.astype("int")
print(F_i)
print(F_i.dtype)

[1 2 3 0]
int64


In [40]:
int_bool = F_i.astype("bool")
print(int_bool)
print(int_bool.dtype)

[ True  True  True False]
bool


In [41]:
float_bool = int_Float.astype("bool")
print(float_bool)
print(float_bool.dtype)

[ True  True  True  True]
bool


## copy vs view

In [50]:
arr = np.array((10,20,30,40,50))
raay = arr.copy()
arr[0]=58
raay[3] = 61
print(arr,raay,sep="\n")
print(id(arr),id(raay),sep="\n")

[58 20 30 40 50]
[10 20 30 61 50]
4457708304
4456954928


In [49]:
arr = np.array((10,20,30,40,50))
carry = arr.view()
arr[0]= 61
carry[3] = 29
print(arr,carry,sep="\n")

[61 20 30 29 50]
[61 20 30 29 50]


In [52]:
#base variable or function called to check whether a array owns it data will reflect the data it doesnt own otherwise none will be printed
arr = np.array((10,20,30,40,50))
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[10 20 30 40 50]


## shape of array

In [57]:
x = np.array(61)
y = np.array((58,5))
z = np.array(((1,2,3),(1,3,4)))
a = np.array((((1,2,3,4,5),(5,6,7,8,9)),((9,8,7,6,4),(5,4,3,2,1))))
b = np.array(((((1,2,3,4,5),(5,6,7,8,9)),((9,8,7,6,4),(5,4,3,2,1))),(((1,2,3,4,5),(5,6,7,8,9)),((9,8,7,6,4),(5,4,3,2,1)))))

In [58]:
print(x.shape,y.shape,z.shape,a.shape,b.shape,sep="\n")

()
(2,)
(2, 3)
(2, 2, 5)
(2, 2, 2, 5)


# DAY 2

## Reshape

In [12]:
import numpy as np

vy= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
yv= vy.reshape(4,3)
print("original array : ",vy,"\nreshaped array : ",yv,sep="\n")

original array : 
[ 1  2  3  4  5  6  7  8  9 10 11 12]

reshaped array : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
yv3 = vy.reshape(2,3,2)
print("3d reshape array\n",yv3)

3d reshape array
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [23]:
print(yv3.base)
print(yv.base,yv,sep="\n")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
#Unknown dimentaion  --- to set accoring to the possible dimenstion only one possible 
vy= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
baby = vy.reshape(3,2,-1)
print(baby)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [33]:
pr = np.array([[1,2,3],[4,5,6]])
r = pr.reshape(-1)
print("flattend array : ",r,sep="\t")

flattend array : 	[1 2 3 4 5 6]


# iteration

In [34]:
vy= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for i in vy:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [40]:
vy= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for i in vy:
    print(i,vy,sep="\n")

1
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2
[ 1  2  3  4  5  6  7  8  9 10 11 12]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
4
[ 1  2  3  4  5  6  7  8  9 10 11 12]
5
[ 1  2  3  4  5  6  7  8  9 10 11 12]
6
[ 1  2  3  4  5  6  7  8  9 10 11 12]
7
[ 1  2  3  4  5  6  7  8  9 10 11 12]
8
[ 1  2  3  4  5  6  7  8  9 10 11 12]
9
[ 1  2  3  4  5  6  7  8  9 10 11 12]
10
[ 1  2  3  4  5  6  7  8  9 10 11 12]
11
[ 1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [41]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x) 

[1 2 3]
[4 5 6]


In [46]:
vy= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = vy.reshape(-1,4)
for i in x:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [48]:
vy= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = vy.reshape(2,2,-1)
for i in y:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [49]:
# iterating to scaler 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [50]:
#nditer() function - helping function for the loops 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [52]:
#iterating array with different data type  , nditer flag = "buffer" - operation doesnt change type on spot need space,op_dtype
vy = np.array((1,2,3,4,5,6,7,8,9,10,11,12))
for x in np.nditer(vy,flags =['buffered'],op_dtypes='S'):
    print(x,x.dtype)


b'1' |S21
b'2' |S21
b'3' |S21
b'4' |S21
b'5' |S21
b'6' |S21
b'7' |S21
b'8' |S21
b'9' |S21
b'10' |S21
b'11' |S21
b'12' |S21


In [56]:
yv =  np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for i in np.nditer(yv[:, ::3]):
    print(i)

1
4
5
8


In [62]:
vy = np.array([10,20,30])
for i, x in np.ndenumerate(vy):
    #print("value of index ",i," is :",x)
    print(f"value of index {i} is {x}")


value of index (0,) is 10
value of index (1,) is 20
value of index (2,) is 30


In [63]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i, x in np.ndenumerate(arr):
    print(f"value of index {i} is {x}")

value of index (0, 0, 0) is 1
value of index (0, 0, 1) is 2
value of index (0, 0, 2) is 3
value of index (0, 1, 0) is 4
value of index (0, 1, 1) is 5
value of index (0, 1, 2) is 6
value of index (1, 0, 0) is 7
value of index (1, 0, 1) is 8
value of index (1, 0, 2) is 9
value of index (1, 1, 0) is 10
value of index (1, 1, 1) is 11
value of index (1, 1, 2) is 12


# Join and stack 

In [65]:
import numpy as np
bahar = np.array([1,2,3])
andar = np.array([9,8,7])
andar_bahar = np.concatenate((bahar,andar))
print(andar_bahar)

[1 2 3 9 8 7]


In [71]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.concatenate((arr1,arr2),axis = 1) #axis = change the layout axis 0 is default
arr4 = np.concatenate((arr1,arr2),axis=0)
print(arr3,"\n\n",arr4)

[[1 2 5 6]
 [3 4 7 8]] 

 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [73]:
#stack ,hstack ,vstack and d-stack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

st = np.stack((arr1,arr2)) #default is vertical stack
sth = np.hstack((arr1,arr2))
stv = np.vstack((arr1,arr2))
std = np.dstack((arr1,arr2))

print(st,sth,stv,std,sep="\n\n")

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[[1 4]
  [2 5]
  [3 6]]]


# splitting array

In [76]:
vy = np.array((1,2,3,4,5,6,7,8,9,10,11,12))
spl = np.array_split(vy,4)
xpl = np.array_split(vy,3)
print(spl)
print(xpl)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


In [78]:
print(spl[0])
print(xpl[0])
print(spl[2])

[1 2 3]
[1 2 3 4]
[7 8 9]


In [80]:
#2d array into three different  2D arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
thr = np.array_split(arr,3)
print(thr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [81]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
thr = np.array_split(arr,3,axis=1)#alternative use hsplit without axis value
print(thr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]


# search

In [85]:
viraj_yash = np.array((1,2,3,55,6,7,55,9,55,21,61,58,200,55))
yash_viraj = np.where(viraj_yash == 55)
print(yash_viraj)

(array([ 3,  6,  8, 13]),)


In [86]:
#for even
vy = np.array((1,2,3,4,5,6,7,8,9,10,11,12))
x = np.where(vy%2 == 0)
print(vy,x,sep="\n")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(array([ 1,  3,  5,  7,  9, 11]),)


In [87]:
vy = np.array((1,2,3,4,5,6,7,8,9,10,11,12))
x = np.where(vy%2 == 1)
print(vy,x,sep="\n")


#search sorted pada tha w3school se ,multivalue 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(array([ 0,  2,  4,  6,  8, 10]),)


# SORT

In [88]:
viraj_yash = np.array((1,2,3,55,6,7,55,9,55,21,61,58,200,55))
print(np.sort(viraj_yash))

[  1   2   3   6   7   9  21  55  55  55  55  58  61 200]


In [89]:
#alphabetical order sort 
pokemon = np.array(("squatle","charmander","bulbasour","pikachu","mewtwo"))
print(np.sort(pokemon))

['bulbasour' 'charmander' 'mewtwo' 'pikachu' 'squatle']


In [93]:
booler= [True,True,True,True,False]
is_staterpokemon = pokemon[booler]
print(is_staterpokemon)

['squatle' 'charmander' 'bulbasour' 'pikachu']


In [94]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr) #otherwise we can use if else conditional statement s


[False  True False  True False  True False]
[2 4 6]
